from lesson_model import Lesson


LLM_FOUNDATION = [
    Lesson(
        concept="Tokens",
        plain="LLMs do not read words directly. They read tokens: small chunks of text that may be words, word parts, punctuation, or spaces.",
        analogy="Like reading a book after every page has been cut into puzzle pieces.",
        frontier="Token counts are the unit of billing and the hard limit of every model. The 2025 race toward million-token contexts and cheaper inference is, underneath, a race over how many tokens you can afford to move at once.",
        bold_move="Build: write a 40-line script that pastes any text, counts its tokens with tiktoken, and prints what it would cost at GPT-4o and Claude prices. Share the number that surprises you.",
    ),
    Lesson(
        concept="Tokenization",
        plain="Tokenization is the process of turning raw text into tokens the model can process.",
        analogy="Like chopping ingredients before cooking. The model cannot cook with whole paragraphs.",
        frontier="Tokenizers quietly decide who the model serves well: the same sentence costs 2-3x more tokens in Hindi or Thai than English, so non-English users pay more for worse context. 'Token equity' is an active fairness debate.",
        bold_move="Provoke: tokenize the same sentence in English and a non-Latin script. Then argue in a paragraph — is a tokenizer a neutral tool or a policy decision about whose language is cheap?",
    ),
    Lesson(
        concept="Vocabulary",
        plain="A model has a fixed vocabulary of token pieces. Every input must be represented using those pieces.",
        analogy="Like building every sentence from a limited box of Lego bricks.",
        frontier="Frontier models keep growing their vocabularies (100k → 200k+ tokens) to swallow code, math, and many languages in fewer pieces. Bigger vocab means shorter sequences but a heavier embedding table — a live efficiency tradeoff.",
        bold_move="Build: feed a tokenizer a rare name, a typo, an emoji, and a snippet of code; chart how many tokens each needs. Post the most absurd token-count you find.",
    ),
    Lesson(
        concept="Embeddings",
        plain="Embeddings turn tokens into vectors: lists of numbers that capture patterns of meaning.",
        analogy="Like giving every concept a coordinate on a giant map of meaning.",
        frontier="Embeddings are the engine of the entire RAG and semantic-search industry. The MTEB leaderboard is fiercely contested, and 2025's frontier is Matryoshka embeddings — one vector you can truncate to trade accuracy for speed.",
        bold_move="Build: embed 20 sentences with sentence-transformers and build a tiny 'find the most similar sentence' search in under 50 lines. Try to break it with a trick query.",
    ),
    Lesson(
        concept="Semantic Space",
        plain="Semantic space is the invisible geometry where meanings live as positions and distances.",
        analogy="Like a galaxy of concepts, where related ideas orbit near each other.",
        frontier="Mechanistic interpretability is trying to read this space directly — Anthropic's sparse-autoencoder work found millions of human-interpretable 'features' (like 'the Golden Gate Bridge') as directions inside it. The geometry is becoming legible.",
        bold_move="Provoke: skim Anthropic's 'Scaling Monosemanticity' summary, then write your best one-paragraph answer to: if concepts are directions in space, is a thought just a point — or a path?",
    ),
    Lesson(
        concept="Similarity",
        plain="Models compare vectors to estimate whether tokens, sentences, or ideas are related.",
        analogy="Like judging whether two songs have a similar mood, even if the notes differ.",
        frontier="Cosine similarity over embeddings is the retrieval step behind nearly every RAG product — and its failures (similar wording, opposite meaning) are why 2025 stacks add rerankers and hybrid search on top.",
        bold_move="Build: find two sentences that mean the OPPOSITE but score as highly similar, and two that mean the SAME but score low. Post both pairs as a 'similarity is not meaning' demo.",
    ),
    Lesson(
        concept="Language as Numbers",
        plain="The model transforms language into numerical structures so computation can happen.",
        analogy="Like translating poetry into coordinates without entirely losing the poem.",
        frontier="The same vector trick now spans modalities — text, images, and audio share embedding spaces, which is how a model can caption a photo or generate one from words. 'Everything is a vector' is the quiet foundation of multimodal AI.",
        bold_move="Provoke: write the strongest case you can that something real is permanently lost when language becomes numbers — then the strongest rebuttal. Decide which you believe.",
    ),
    Lesson(
        concept="Next Token Prediction",
        plain="The core training task is predicting the next token from previous tokens.",
        analogy="Like finishing someone's sentence, but at planetary scale.",
        frontier="The big 2024-2025 surprise: this one humble objective, scaled up, produces planning, coding, and chain-of-thought reasoning. The open question dividing the field — is 'just predicting the next token' enough for real reasoning, or a ceiling?",
        bold_move="Reach out: email or post a short, sincere question to an AI researcher you admire — 'Do you think next-token prediction alone can reach genuine reasoning, or do we need a new objective? Why?' Draft: two sentences of what you're learning, then the one question. Send it.",
    ),
    Lesson(
        concept="Attention",
        plain="Attention lets the model decide which tokens matter most when processing the current token.",
        analogy="Like knowing which voice to listen to in a crowded room.",
        frontier="Attention is the most-optimized operation in AI. FlashAttention (now v3) rewrote it to be memory-aware and unlocked today's long contexts; it's why a model can attend over a whole book without melting the GPU.",
        bold_move="Build: implement softmax-attention over 4 toy vectors in pure numpy (no libraries) and visualize the weights as a bar chart. Watch attention concentrate when you change one score.",
    ),
    Lesson(
        concept="Self-Attention",
        plain="Self-attention lets every token look at other tokens in the same context and update its meaning.",
        analogy="Like every person in a meeting listening to every other person before forming an opinion.",
        frontier="Self-attention's cost grows with the square of the sequence length — the central bottleneck of scale. The whole 2025 zoo of alternatives (Mamba, linear/state-space models) exists to dodge that quadratic wall.",
        bold_move="Provoke: self-attention compares every token to every other token. In one paragraph, argue from first principles why that O(n²) cost might be fundamental to understanding — or just an accident of the architecture we happened to pick.",
    ),
    Lesson(
        concept="Context Windows",
        plain="A context window is the amount of text the model can consider at once.",
        analogy="Like the size of a desk where the model can lay out papers while thinking.",
        frontier="Windows exploded from 4k to 1M+ tokens in two years — but 'lost in the middle' research shows models still ignore information buried mid-context. Bigger desk, same wandering attention. Long-context evals are now their own field.",
        bold_move="Build: paste a long document, then hide one odd fact in the exact middle and ask a model to retrieve it. Repeat with the fact at the start and end. Report where it fails.",
    ),
    Lesson(
        concept="Positional Encoding",
        plain="Because transformers process tokens in parallel, they need position information to know order.",
        analogy="Like giving every word a seat number in a theater.",
        frontier="RoPE (rotary position embeddings) is the quiet hero of long context — almost every 2024-2025 open model uses it, and tricks like position interpolation are how a model trained on 8k tokens suddenly handles 128k.",
        bold_move="Provoke: 'dog bites man' and 'man bites dog' use identical tokens. Write why position information is not a detail but the difference between meaning and nonsense — and what that says about how fragile understanding is.",
    ),
    Lesson(
        concept="Transformers",
        plain="Transformers are the architecture behind modern LLMs, built around attention and parallel processing.",
        analogy="Like a massive committee where each token consults every other token efficiently.",
        frontier="'Attention Is All You Need' (2017) is now one of the most-cited papers in science. Eight years on, the live question is whether anything dethrones it — Mamba and hybrid architectures are the most serious challengers yet.",
        bold_move="Reach out: pick one author of a recent 'transformer alternative' paper (e.g. Mamba) and send a 3-line note. Draft: 'I'm learning LLMs from the ground up. Your work on {X} made me wonder — what's the one thing transformers do that yours can't yet? Thank you for the paper.'",
    ),
    Lesson(
        concept="Information Flow",
        plain="Inside a transformer, token representations are repeatedly updated through attention and neural layers.",
        analogy="Like revising a rough interpretation again and again until it becomes richer.",
        frontier="Tracing this flow is the heart of interpretability — 'circuits' work follows how facts and behaviors move through specific layers and heads. We're starting to point at where in the stack a model 'decides' something.",
        bold_move="Build: load a small model with transformers, run one sentence, and print the hidden-state vector for one token at layer 1 vs the last layer. Eyeball how much it changed.",
    ),
    Lesson(
        concept="Pretraining",
        plain="Pretraining teaches a model broad language patterns by exposing it to huge amounts of text.",
        analogy="Like reading a giant library before ever being assigned a specific job.",
        frontier="The field is hitting a 'data wall' — we may be running out of high-quality human text. The 2025 bet is synthetic data: models generating their own training data, with a real risk of model-collapse if it's done carelessly.",
        bold_move="Provoke: if we run out of human text and train models on AI-generated text, what exactly degrades — and what (if anything) improves? Argue your position in a short post.",
    ),
    Lesson(
        concept="Loss Functions",
        plain="A loss function measures how wrong the model's prediction was.",
        analogy="Like a teacher marking how far your answer was from the correct one.",
        frontier="Cross-entropy still trains the base model, but the frontier loss is now about preferences, not next-tokens — DPO and its successors directly optimize 'humans liked this answer more,' collapsing a whole RLHF pipeline into one loss.",
        bold_move="Build: compute cross-entropy by hand in 5 lines of numpy for a confident-correct, confident-wrong, and unsure prediction. See why confidence in the wrong answer is punished hardest.",
    ),
    Lesson(
        concept="Gradient Descent",
        plain="Gradient descent adjusts model parameters to reduce future mistakes.",
        analogy="Like walking downhill in fog by feeling which direction slopes lower.",
        frontier="Every frontier model is still trained by this 1840s idea, scaled to trillions of steps. The 2024-2025 action is in optimizers and stability tricks (muP, careful warmup) that keep a billion-dollar run from diverging halfway through.",
        bold_move="Build: minimize f(x)=x² from x=4 in a 6-line Python loop, printing each step. Then sabotage it with a huge learning rate and watch it explode. Screenshot both.",
    ),
    Lesson(
        concept="Parameters",
        plain="Parameters are the internal numbers adjusted during training. They store learned patterns.",
        analogy="Like billions of tiny knobs tuned by experience.",
        frontier="The whole open-weights movement (Llama, Mistral, DeepSeek) is a fight over who controls these numbers. Quantization — squeezing parameters from 16 bits to 4 — is what lets a frontier-class model run on your laptop.",
        bold_move="Provoke: a model's entire 'knowledge' is a blob of numbers nobody can read. Argue whether shipping open weights is closer to publishing a book or releasing a tool — and what should be allowed.",
    ),
    Lesson(
        concept="Scaling Laws",
        plain="Scaling laws describe how model performance often improves predictably with more data, compute, and parameters.",
        analogy="Like discovering that bigger telescopes reveal more structure in the sky.",
        frontier="The plot twist of 2024-2025: the action moved from training scale to inference-time compute. Reasoning models (o-series and peers) get smarter by thinking longer at answer time — a brand-new scaling axis Chinchilla never described.",
        bold_move="Reach out: post a sharp question publicly (X / a forum) — 'Chinchilla scaled training compute. Reasoning models scale test-time compute. Is there a unified law connecting them, or are these different curves?' Tag someone who'd know. Invite an answer.",
    ),
    Lesson(
        concept="Emergent Abilities",
        plain="Emergent abilities are capabilities that appear suddenly when models reach enough scale or training quality.",
        analogy="Like water becoming steam after crossing a temperature threshold.",
        frontier="A genuine live controversy: a Stanford paper argued emergence is partly a 'mirage' caused by harsh all-or-nothing metrics. Whether new abilities truly appear or just become measurable is unsettled — and it matters for predicting what's next.",
        bold_move="Provoke: read the one-line claim of both sides (emergence is real vs. a metric artifact) and write which you find more convincing and the single experiment that would change your mind.",
    ),
    Lesson(
        concept="Learning Review",
        plain="An LLM learns by compressing patterns from text into parameters through repeated prediction and correction.",
        analogy="Like distilling a library into a strange, compressed intuition machine.",
        frontier="'Compression is intelligence' has become a serious research stance — some argue a model's ability to compress text is the cleanest measure of how much it understands. Your one-paragraph summary is doing the same thing the model does.",
        bold_move="Build: write the tightest one-paragraph explanation of pretraining + loss + parameters that a smart 12-year-old would get. Send it to a non-technical friend and fix whatever they didn't understand.",
    ),
    Lesson(
        concept="Hallucinations",
        plain="Hallucinations happen when a model produces plausible text that is not grounded in truth.",
        analogy="Like a confident storyteller filling gaps with invented details.",
        frontier="2025's most-discussed framing: a model has no built-in sense of 'I don't know.' Work on calibration and 'honest uncertainty' tries to make confidence track correctness — arguably the single biggest blocker to trusting AI in high-stakes use.",
        bold_move="Build: ask a model for 5 citations on an obscure topic, then check each one. Tally how many are real, half-real, and fully invented. Post your hallucination rate.",
    ),
    Lesson(
        concept="Context Poisoning",
        plain="Context poisoning happens when misleading or malicious context steers the model toward bad outputs.",
        analogy="Like giving someone false clues before asking them to solve a mystery.",
        frontier="Indirect prompt injection is now the #1 security risk for AI agents (top of the OWASP LLM list): a poisoned web page or email can hijack an agent reading it. As agents get tools, this stops being academic.",
        bold_move="Provoke: design (on paper, ethically) the smallest poisoned snippet that could hijack a web-browsing agent — then write the defense you'd ship. Think like attacker AND defender.",
    ),
    Lesson(
        concept="Retrieval Failures",
        plain="Retrieval failures happen when the system does not fetch or use the right information.",
        analogy="Like having the right book in the library but pulling the wrong shelf.",
        frontier="RAG's weakest link is retrieval, not generation — which is why 2025 production stacks bolt on rerankers, hybrid (keyword + vector) search, and 'agentic retrieval' that searches in a loop. Most 'the AI was wrong' bugs are actually retrieval bugs.",
        bold_move="Build: write a query where the right answer exists in your docs but plain vector search misses it (synonyms, acronyms). Then fix it with one change and document the before/after.",
    ),
    Lesson(
        concept="Goodhart's Law in AI",
        plain="When a metric becomes the target, systems may optimize the metric while losing the real goal.",
        analogy="Like studying only to score well while understanding nothing.",
        frontier="This is the beating heart of the alignment problem: reward models get 'reward hacked,' and benchmarks get gamed by training on their data ('contamination'). Every leaderboard jump now invites the question — real, or Goodharted?",
        bold_move="Provoke: pick a real AI benchmark and describe exactly how you'd inflate the score without making the model better. Then propose one eval that resists your own hack.",
    ),
    Lesson(
        concept="Distribution Shift",
        plain="Distribution shift happens when a model faces inputs different from what it learned from.",
        analogy="Like training for piano recitals and then being asked to improvise jazz on stage.",
        frontier="As models flood the internet with text, tomorrow's models train on today's outputs — a slow, self-inflicted distribution shift. Monitoring for 'the world changed under my model' is now core MLOps, not an afterthought.",
        bold_move="Build: feed a model deliberately out-of-distribution input (heavy slang, a made-up format, a brand-new event) and document the exact moment it stumbles. Find its edge.",
    ),
    Lesson(
        concept="Alignment",
        plain="Alignment tries to make model behavior match human intentions, values, and safety needs.",
        analogy="Like training a brilliant assistant not just to answer, but to answer responsibly.",
        frontier="Alignment moved from RLHF (humans rate answers) toward RLAIF and Constitutional AI (models critique themselves against written principles), plus 'deliberative alignment' baked into reasoning models. The frontier question: can a system help align systems smarter than itself?",
        bold_move="Reach out: email someone working in AI safety with one honest question. Draft: 'I'm self-studying how LLMs work. Constitutional AI has models critique themselves — what stops a model from learning to *appear* aligned rather than *be* aligned? Genuinely curious how you think about this.'",
    ),
    Lesson(
        concept="Evaluation",
        plain="Evaluation tests whether a model actually performs well, but measuring understanding is difficult.",
        analogy="Like judging a student who can sound brilliant without knowing the material.",
        frontier="Static benchmarks are saturating and leaking, so eval shifted to LLM-as-judge and live human-vote arenas (LMArena). But 'who judges the judge?' is unsolved — model judges have their own biases (length, style). Evaluation is now a research field, not a checkbox.",
        bold_move="Build: write ONE question whose right answer can't be reached by paraphrasing the prompt, then test it on two models and grade them yourself. Did your eval separate understanding from fluency?",
    ),
    Lesson(
        concept="Prompt Engineering",
        plain="Prompt engineering is the practice of shaping instructions and context to get better model behavior.",
        analogy="Like briefing a collaborator before asking for work.",
        frontier="Chain-of-thought ('think step by step') was a prompt trick that became an architecture — reasoning models now do it internally. The frontier moved up a level to context engineering: managing memory, tools, and retrieved context across a whole agent run.",
        bold_move="Build: take one vague prompt you actually use and rewrite it with a role, goal, constraints, and an output format. Run both versions and keep the diff as proof of the gain.",
    ),
    Lesson(
        concept="Systems Thinking for AI",
        plain="LLMs are not isolated minds. They are components inside larger systems involving tools, data, users, incentives, and feedback.",
        analogy="Like an engine inside a vehicle, powerful but useless without steering, fuel, and brakes.",
        frontier="2025 is the year of agents — the model became one part of a loop with tools, memory, retrieval, and other agents. The hard problems are now systems problems: orchestration, evaluation, cost, and trust, not just the model.",
        bold_move="Build: map one real AI product as a full system on a single page — model, data, user, interface, feedback loop, and one failure mode each. Then circle the weakest link and propose a fix.",
    ),
]
