from lesson_model import Lesson


LESSONS = [
    Lesson(
        concept="Tokens",
        plain="LLMs do not read words directly. They read tokens: small chunks of text that may be words, word parts, punctuation, or spaces.",
        analogy="Like reading a book after every page has been cut into puzzle pieces.",
        exercise="Take the sentence 'I love learning.' Guess how it might be split into tokens.",
    ),
    Lesson(
        concept="Tokenization",
        plain="Tokenization is the process of turning raw text into tokens the model can process.",
        analogy="Like chopping ingredients before cooking. The model cannot cook with whole paragraphs.",
        exercise="Why might 'unbelievable' be split into smaller pieces instead of treated as one word?",
    ),
    Lesson(
        concept="Vocabulary",
        plain="A model has a fixed vocabulary of token pieces. Every input must be represented using those pieces.",
        analogy="Like building every sentence from a limited box of Lego bricks.",
        exercise="What might happen when a model sees a rare name, typo, or foreign word?",
    ),
    Lesson(
        concept="Embeddings",
        plain="Embeddings turn tokens into vectors: lists of numbers that capture patterns of meaning.",
        analogy="Like giving every concept a coordinate on a giant map of meaning.",
        exercise="Why would 'king' and 'queen' be closer than 'king' and 'banana'?",
    ),
    Lesson(
        concept="Semantic Space",
        plain="Semantic space is the invisible geometry where meanings live as positions and distances.",
        analogy="Like a galaxy of concepts, where related ideas orbit near each other.",
        exercise="Name three concepts that would sit near 'school' in semantic space.",
    ),
    Lesson(
        concept="Similarity",
        plain="Models compare vectors to estimate whether tokens, sentences, or ideas are related.",
        analogy="Like judging whether two songs have a similar mood, even if the notes differ.",
        exercise="Why are 'doctor' and 'hospital' similar even though they are different words?",
    ),
    Lesson(
        concept="Language as Numbers",
        plain="The model transforms language into numerical structures so computation can happen.",
        analogy="Like translating poetry into coordinates without entirely losing the poem.",
        exercise="What is gained and lost when language becomes numbers?",
    ),
    Lesson(
        concept="Next Token Prediction",
        plain="The core training task is predicting the next token from previous tokens.",
        analogy="Like finishing someone's sentence, but at planetary scale.",
        exercise="Why can predicting the next token produce behavior that feels like reasoning?",
    ),
    Lesson(
        concept="Attention",
        plain="Attention lets the model decide which tokens matter most when processing the current token.",
        analogy="Like knowing which voice to listen to in a crowded room.",
        exercise="Explain attention using a dinner table conversation.",
    ),
    Lesson(
        concept="Self-Attention",
        plain="Self-attention lets every token look at other tokens in the same context and update its meaning.",
        analogy="Like every person in a meeting listening to every other person before forming an opinion.",
        exercise="In 'The animal did not cross the street because it was tired,' what should 'it' attend to?",
    ),
    Lesson(
        concept="Context Windows",
        plain="A context window is the amount of text the model can consider at once.",
        analogy="Like the size of a desk where the model can lay out papers while thinking.",
        exercise="What breaks when the needed information falls outside the context window?",
    ),
    Lesson(
        concept="Positional Encoding",
        plain="Because transformers process tokens in parallel, they need position information to know order.",
        analogy="Like giving every word a seat number in a theater.",
        exercise="Why do 'dog bites man' and 'man bites dog' mean different things?",
    ),
    Lesson(
        concept="Transformers",
        plain="Transformers are the architecture behind modern LLMs, built around attention and parallel processing.",
        analogy="Like a massive committee where each token consults every other token efficiently.",
        exercise="Why was attention so important for scaling language models?",
    ),
    Lesson(
        concept="Information Flow",
        plain="Inside a transformer, token representations are repeatedly updated through attention and neural layers.",
        analogy="Like revising a rough interpretation again and again until it becomes richer.",
        exercise="How does a token's meaning change after seeing surrounding context?",
    ),
    Lesson(
        concept="Pretraining",
        plain="Pretraining teaches a model broad language patterns by exposing it to huge amounts of text.",
        analogy="Like reading a giant library before ever being assigned a specific job.",
        exercise="What kinds of knowledge can be absorbed through pretraining?",
    ),
    Lesson(
        concept="Loss Functions",
        plain="A loss function measures how wrong the model's prediction was.",
        analogy="Like a teacher marking how far your answer was from the correct one.",
        exercise="Why does a model need a numerical way to measure mistakes?",
    ),
    Lesson(
        concept="Gradient Descent",
        plain="Gradient descent adjusts model parameters to reduce future mistakes.",
        analogy="Like walking downhill in fog by feeling which direction slopes lower.",
        exercise="Why is tiny repeated improvement powerful at scale?",
    ),
    Lesson(
        concept="Parameters",
        plain="Parameters are the internal numbers adjusted during training. They store learned patterns.",
        analogy="Like billions of tiny knobs tuned by experience.",
        exercise="Why is model knowledge hard to inspect directly if it is stored in parameters?",
    ),
    Lesson(
        concept="Scaling Laws",
        plain="Scaling laws describe how model performance often improves predictably with more data, compute, and parameters.",
        analogy="Like discovering that bigger telescopes reveal more structure in the sky.",
        exercise="Why might scale create new capabilities instead of just better memorization?",
    ),
    Lesson(
        concept="Emergent Abilities",
        plain="Emergent abilities are capabilities that appear suddenly when models reach enough scale or training quality.",
        analogy="Like water becoming steam after crossing a temperature threshold.",
        exercise="What is one AI ability that seems more than simple autocomplete?",
    ),
    Lesson(
        concept="Learning Review",
        plain="An LLM learns by compressing patterns from text into parameters through repeated prediction and correction.",
        analogy="Like distilling a library into a strange, compressed intuition machine.",
        exercise="Explain pretraining, loss, and parameters in one paragraph.",
    ),
    Lesson(
        concept="Hallucinations",
        plain="Hallucinations happen when a model produces plausible text that is not grounded in truth.",
        analogy="Like a confident storyteller filling gaps with invented details.",
        exercise="Why does fluency make hallucinations more dangerous?",
    ),
    Lesson(
        concept="Context Poisoning",
        plain="Context poisoning happens when misleading or malicious context steers the model toward bad outputs.",
        analogy="Like giving someone false clues before asking them to solve a mystery.",
        exercise="How could one bad document distort an AI answer?",
    ),
    Lesson(
        concept="Retrieval Failures",
        plain="Retrieval failures happen when the system does not fetch or use the right information.",
        analogy="Like having the right book in the library but pulling the wrong shelf.",
        exercise="Why can a RAG system fail even if the answer exists somewhere?",
    ),
    Lesson(
        concept="Goodhart's Law in AI",
        plain="When a metric becomes the target, systems may optimize the metric while losing the real goal.",
        analogy="Like studying only to score well while understanding nothing.",
        exercise="How might an AI evaluator reward fluency instead of real understanding?",
    ),
    Lesson(
        concept="Distribution Shift",
        plain="Distribution shift happens when a model faces inputs different from what it learned from.",
        analogy="Like training for piano recitals and then being asked to improvise jazz on stage.",
        exercise="Where might an LLM fail outside familiar patterns?",
    ),
    Lesson(
        concept="Alignment",
        plain="Alignment tries to make model behavior match human intentions, values, and safety needs.",
        analogy="Like training a brilliant assistant not just to answer, but to answer responsibly.",
        exercise="Why is helpfulness alone not enough?",
    ),
    Lesson(
        concept="Evaluation",
        plain="Evaluation tests whether a model actually performs well, but measuring understanding is difficult.",
        analogy="Like judging a student who can sound brilliant without knowing the material.",
        exercise="Design one question that separates paraphrase from understanding.",
    ),
    Lesson(
        concept="Prompt Engineering",
        plain="Prompt engineering is the practice of shaping instructions and context to get better model behavior.",
        analogy="Like briefing a collaborator before asking for work.",
        exercise="Rewrite a vague prompt into a precise one with context, goal, and constraints.",
    ),
    Lesson(
        concept="Systems Thinking for AI",
        plain="LLMs are not isolated minds. They are components inside larger systems involving tools, data, users, incentives, and feedback.",
        analogy="Like an engine inside a vehicle, powerful but useless without steering, fuel, and brakes.",
        exercise="Map one AI product as a system: model, data, user, interface, feedback, failure mode.",
    ),
]